# SwiftLint конфигурация (улучшенная версия)
# https://realm.github.io/SwiftLint/

# Отключенные правила
disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - trailing_newline
  - identifier_name            # Разрешаем короткие имена (i, j)
  - type_name                  # Разрешаем _ в именах типов
  - function_body_length       # Разрешаем длинные функции
  - cyclomatic_complexity      # Разрешаем сложные функции

# Включенные правила
opt_in_rules:
  - empty_count
  - empty_string
  - redundant_nil_coalescing
  - syntactic_sugar
  - force_unwrapping           # Запрещаем ! для распаковки опционалов
  - force_try                  # Запрещаем try! для обработки ошибок
  - closure_end_indentation    # Проверяем отступы закрывающих скобок
  - closure_spacing            # Проверяем пробелы в замыканиях
  - collection_alignment       # Выравнивание коллекций
  - contains_over_filter_count # Используем contains вместо filter().count > 0
  - redundant_type_annotation  # Убираем избыточные типы
  - mark                       # Требуем использовать // MARK: -

# Исключенные папки
excluded:
  - Pods
  - build
  - .build
  - DerivedData
  - fastlane
  - .git
  - CocktailFinder-SwiftAppUITests

# Включенные папки
included:
  - CocktailFinder-SwiftApp
  - CocktailFinder-SwiftAppTests

# Мягкие настройки
line_length:
  warning: 200
  error: 300
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1000
  error: 2000

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 1000

# Настройка правила force_unwrapping
force_unwrapping:
  severity: error

# Убираем пользовательские правила для простоты
# custom_rules:
#   no_print:
#     name: "No Print Statements"
#     regex: "print\\("
#     message: "Используйте логгер вместо print()"
#     severity: warning 