# SwiftLint конфигурация (мягкая версия для начала)
# https://realm.github.io/SwiftLint/

# Отключенные правила (больше для простоты)
disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - force_unwrapping           # Разрешаем ! в тестах
  - force_try                  # Разрешаем try! в тестах  
  - identifier_name            # Разрешаем короткие имена (i, j)
  - type_name                  # Разрешаем _ в именах типов
  - function_body_length       # Разрешаем длинные функции
  - cyclomatic_complexity      # Разрешаем сложные функции
  - trailing_newline           # Не требуем пустую строку в конце

# Включенные простые правила
opt_in_rules:
  - empty_count
  - empty_string
  - redundant_nil_coalescing
  - syntactic_sugar

# Исключенные папки
excluded:
  - Pods
  - build
  - .build
  - DerivedData
  - fastlane
  - .git

# Включенные папки
included:
  - CocktailFinder-SwiftApp
  - CocktailFinder-SwiftAppTests

# Мягкие настройки
line_length:
  warning: 200
  error: 300
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1000
  error: 2000

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 1000

# Убираем пользовательские правила для простоты
# custom_rules:
#   no_print:
#     name: "No Print Statements"
#     regex: "print\\("
#     message: "Используйте логгер вместо print()"
#     severity: warning 