name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  # Параллельные задачи для ускорения
  lint:
    name: SwiftLint
    runs-on: macos-latest
    # Пропускаем, если в сообщении коммита есть [skip ci] или [ci skip]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint --reporter github-actions-logging

  unit-tests:
    name: Unit Tests
    runs-on: macos-latest
    # Пропускаем, если в сообщении коммита есть [skip ci] или [ci skip]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        destination: 
          - 'platform=iOS Simulator,name=iPhone 16,OS=latest'
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show available simulators
      run: xcrun simctl list devicetypes
    
    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/.cache/org.swift.swiftpm/
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.xcodeproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
    
    - name: Run Tests
      run: |
        set -o pipefail && xcodebuild test \
          -project CocktailFinder-SwiftApp.xcodeproj \
          -scheme CocktailFinder-SwiftApp \
          -destination '${{ matrix.destination }}' \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults.xcresult \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults.xcresult
        retention-days: 30

  code-coverage:
    name: Code Coverage
    runs-on: macos-latest
    needs: unit-tests
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: .
    
    - name: Generate Coverage Report
      run: |
        if [ -f TestResults.xcresult ]; then
          xcrun xccov view --report --json TestResults.xcresult > coverage.json || echo "Failed to generate coverage JSON"
          xcrun xccov view --report TestResults.xcresult || echo "Failed to generate coverage report"
        else
          echo "TestResults.xcresult file not found"
          ls -la
          echo "Creating empty coverage file"
          echo "{}" > coverage.json
        fi
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.json
        fail_ci_if_error: false

  build-release:
    name: Build Release
    runs-on: macos-latest
    needs: [lint, unit-tests]
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build Release
      run: |
        xcodebuild clean build \
          -project CocktailFinder-SwiftApp.xcodeproj \
          -scheme CocktailFinder-SwiftApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""

  notification:
    name: Notify Results
    runs-on: macos-latest
    needs: [lint, unit-tests, code-coverage]
    if: always() && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')
    
    steps:
    - name: Notify Success
      if: needs.unit-tests.result == 'success'
      run: echo "✅ Все тесты прошли успешно!"
      
    - name: Notify Failure  
      if: needs.unit-tests.result == 'failure'
      run: echo "❌ Тесты провалились!" 