name: Simple iOS Tests

on:
  push:
    branches: [ main ]

jobs:
  simple-test:
    name: Simple Build Test
    runs-on: macos-latest
    # Пропускаем, если в сообщении коммита есть [skip ci] или [ci skip]
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: List project contents
      run: ls -la
    
    - name: Check project file
      run: |
        echo "Checking project file..."
        ls -la CocktailFinder-SwiftApp.xcodeproj/
        file CocktailFinder-SwiftApp.xcodeproj/project.pbxproj
    
    - name: Simple build only
      run: |
        xcodebuild -project CocktailFinder-SwiftApp.xcodeproj \
                   -scheme CocktailFinder-SwiftApp \
                   -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
                   clean build 